// Full content for the "Prompting 101: How to Actually Get Good Answers"
// article. Same typed-block approach as aiVsMlVsDl.ts — see that file's
// header comment for why.
//
// The 6 supporting images (img-1..img-6) were generated by the user and
// couldn't be previewed before placement — this session's image budget
// was exhausted by the time they arrived. They're spread across natural
// conceptual breaks (the four ingredients, constraints, "ask me questions
// first", trade-offs, structure, bad-vs-good examples) rather than
// verified against specific content. Alt text is deliberately generic for
// the same reason — if a placement or alt text turns out to be off, it's
// a quick fix once actually seen.

import type { ArticleBlock } from "./aiVsMlVsDl";
import { assetUrl } from "@/lib/assetUrl";

export const heroImage = { src: assetUrl("/articles/prompting-101/hero.png"), alt: "Illustration for Prompting 101: how to get good answers from AI.", width: 1212, height: 1298 };

export const blocks: ArticleBlock[] = [
  { type: "p", text: "You ask an AI a question. You get an answer. Sometimes it's exactly what you wanted. Other times, you get three paragraphs of generic advice, a list you didn't ask for, or an answer that sounds confident but completely misses the point." },
  { type: "p", text: "So you try again: \"No, that's not what I meant.\" And again: \"Be more specific.\" And eventually: \"Forget it.\" Sound familiar?" },
  { type: "callout", text: "The interesting part is that the problem isn't always the AI model. Very often, it's the way we asked the question." },
  { type: "p", text: "Learning how to communicate with AI is becoming a surprisingly useful skill — not because you need to learn complicated \"prompt engineering,\" but because AI can only work with the information and direction you give it. The good news: you don't need to become a prompt engineer. You just need a handful of habits." },

  { type: "h2", text: "1. The biggest misconception about prompting" },
  { type: "p", text: "When people hear \"prompt engineering,\" they sometimes imagine something highly technical — temperature, chain-of-thought, few-shot, system prompt, role conditioning. For most everyday users, forget all of that." },
  { type: "p", text: "A good prompt is usually just a clear request with enough context to understand what you actually want. Think about asking another human for help. Compare \"Tell me about cars\" with \"I'm looking to buy an automatic SUV in Bangalore, with a budget of around ₹20–22 lakh. Safety and driving experience matter more to me than fuel economy. I mostly drive in the city but take occasional highway trips. What should I consider?\" The second question gives the person something to work with. AI is no different." },

  { type: "h2", text: "2. The golden rule: AI doesn't know what you didn't tell it" },
  { type: "p", text: "Imagine walking into a restaurant and saying \"Give me something good.\" The waiter has a problem — good for whom? Maybe you're vegetarian, hate spicy food, allergic to peanuts, have ₹500, or are celebrating an anniversary. The waiter can't read your mind. AI can't either." },
  { type: "p", text: "This is why context matters. Instead of \"Suggest a laptop,\" try \"Suggest a laptop under ₹1 lakh for software development. I'll use it mainly for Python, Docker and occasional local AI inference. Battery life and portability matter because I travel frequently.\" Suddenly, the AI has constraints to work with." },

  { type: "image", src: assetUrl("/articles/prompting-101/img-1.jpeg"), alt: "Illustration accompanying the section on giving AI context — a visual metaphor for a vague request versus a well-specified one." },

  { type: "h2", text: "3. The four ingredients of a good prompt" },
  { type: "p", text: "For most everyday tasks, you can think about four things: what do you want, what does the AI need to know, what constraints matter, and what should the answer look like. That's it — you don't need a 500-word prompt every time." },
  { type: "p", text: "A useful template: \"I want [GOAL]. Here's the relevant context: [CONTEXT]. My constraints are [CONSTRAINTS]. Give me the answer as [FORMAT].\" For example: \"I want to choose a health insurance plan for my parents. They are both in their 60s and I want broad hospital coverage. My budget is ₹50,000 per year. Compare five options in a table and explain the major trade-offs in simple language.\" Much better than \"Best health insurance?\"" },

  { type: "h2", text: "4. Start with the outcome, not the topic" },
  { type: "p", text: "People often tell AI the topic instead of the goal. \"Machine Learning\" — what are you asking? A definition? A beginner tutorial? Interview prep? Career advice? A research summary? Code? A project idea?" },
  { type: "p", text: "Instead, say \"I'm completely new to Machine Learning. Explain it in simple language using everyday examples. Assume I don't have a technical background.\" Now the AI knows what success looks like. Topic: \"Machine Learning.\" Goal: \"Explain Machine Learning to a non-technical person who has never studied computer science.\" The second is dramatically more useful." },

  { type: "h2", text: "5. Context is your secret weapon" },
  { type: "p", text: "AI can generate an answer without context, but the more relevant context you provide, the more tailored the answer can become. \"Should I do an MBA?\" is an enormous question. Now add: \"I'm 34, have around 10 years of experience in AI, currently work as a Staff AI Scientist, and I'm considering an MBA mainly for business understanding and future leadership roles. I'm not primarily looking for a career switch. Compare whether the time and cost would make sense.\" Now the question is much easier to answer meaningfully." },
  { type: "p", text: "But there's a balance — more context isn't always better. You don't need to tell the AI your entire life story. Give it relevant context." },

  { type: "h2", text: "6. Don't give the AI information just because you have it" },
  { type: "p", text: "This is an underrated prompting skill. If you're asking \"Help me choose a camera,\" you probably don't need to provide your childhood hobbies, favourite movie, office location, or university GPA — unless they somehow affect the decision." },
  { type: "p", text: "Instead, provide budget, type of photography, experience level, camera system, weight preference, and whether you already own lenses. The goal isn't maximum information — it's maximum relevant information." },

  { type: "h2", text: "7. Constraints make answers dramatically better" },
  { type: "p", text: "\"Give me side-income ideas\" gets you: start a YouTube channel, start a blog, freelance, start a newsletter, sell courses. Not necessarily bad — just generic." },
  { type: "p", text: "Now add: \"I can spend a maximum of 3 hours a day. My main job is already demanding, so I don't want something mentally exhausting. I'd prefer something that can start generating income relatively quickly and doesn't require building a large audience.\" Now the AI has a filter." },
  { type: "list", items: ["Money — \"Budget: ₹20,000.\"", "Time — \"I can spend 5 hours a week.\"", "Experience — \"I'm a complete beginner.\"", "Location — \"I'm based in Bangalore.\"", "Preferences — \"I prefer remote work.\"", "Deadline — \"I need something ready by Friday.\""] },
  { type: "callout", text: "Constraints turn \"Give me ideas\" into \"Solve this particular problem.\"" },

  { type: "image", src: assetUrl("/articles/prompting-101/img-2.jpeg"), alt: "Illustration accompanying the section on constraints — a visual metaphor for how limits and preferences narrow a broad request into a focused one." },

  { type: "h2", text: "8. Tell AI what \"good\" means" },
  { type: "p", text: "\"Recommend a car\" — what does good mean? Good mileage? Safety? Performance? Luxury? Reliability? Resale value? Off-road capability? Low maintenance? The AI has to guess." },
  { type: "p", text: "Instead: \"I'm looking for an automatic SUV under ₹22 lakh on-road. My priorities, in order, are safety, driving experience, highway stability and road presence. I mostly drive in the city but take long highway trips several times a year.\" Now you've defined your version of good — one of the most powerful prompting habits there is." },

  { type: "h2", text: "9. Ask for the format you actually want" },
  { type: "p", text: "AI doesn't just need to know what you want — it can also help to know how you want it presented. Compare \"Explain mutual funds\" with \"Explain mutual funds to someone who understands savings accounts and fixed deposits but has never invested in mutual funds. Use a simple analogy, then give me a five-point summary.\" The second tells the AI the audience, complexity, structure, and desired length." },
  { type: "list", items: ["\"Give me a table.\"", "\"Keep it under 500 words.\"", "\"Use bullet points.\"", "\"Explain it like I'm a beginner.\"", "\"Give me three examples.\"", "\"Start with the conclusion.\"", "\"Separate facts from assumptions.\"", "\"Give me the pros and cons.\""] },

  { type: "h2", text: "10. One surprisingly powerful phrase: \"Ask me questions first\"" },
  { type: "p", text: "Sometimes you don't know enough about the problem yourself to write a good prompt. That's okay. Tell the AI: \"I want to buy a laptop, but I'm not sure what specifications I need. Ask me the questions you need before recommending anything.\" Now the AI becomes part of the discovery process." },
  { type: "list", items: ["Travel — \"Help me plan a trip. Ask me the questions you need before creating the itinerary.\"", "Career — \"Help me decide whether I should change careers. Ask me the questions you need to understand my situation first.\"", "Business — \"I want to start a small business. Interview me about my skills, budget and constraints before suggesting ideas.\""] },
  { type: "p", text: "This is often better than trying to anticipate every piece of information yourself." },

  { type: "h2", text: "11. Don't try to write the perfect prompt in one shot" },
  { type: "p", text: "This is probably the biggest practical lesson. You don't need the perfect first prompt — conversation itself is a tool. Start with \"Explain RAG to me.\" Then \"That's too technical. Explain it using an example from a company.\" Then \"Now explain what happens technically behind the scenes.\" Then \"Give me a simple architecture diagram.\"" },
  { type: "callout", text: "You have effectively built a better answer through iteration. Think of prompting as a conversation rather than a command." },

  { type: "image", src: assetUrl("/articles/prompting-101/img-3.jpeg"), alt: "Illustration accompanying the section on iterating with AI — a visual metaphor for refining an answer over several exchanges rather than one perfect prompt." },

  { type: "h2", text: "12. Follow-up questions are not a failure" },
  { type: "p", text: "Suppose the AI gives you an answer and you say \"This is too generic.\" That's useful feedback. You can say \"Make it specific to someone with 10 years of AI experience,\" or \"Focus only on options available in India,\" or \"You gave me 20 options. Narrow this down to five and explain the trade-offs,\" or \"Don't repeat the background. Just answer the question.\"" },
  { type: "p", text: "You are steering the conversation. That's one of the biggest differences between using AI casually and using it effectively." },

  { type: "h2", text: "13. Ask AI to challenge your assumptions" },
  { type: "p", text: "Most people ask AI \"Tell me why my idea is good.\" Instead, try \"Critically evaluate this idea. Tell me what I'm missing, what could go wrong, and what assumptions I'm making.\"" },
  { type: "p", text: "For example: \"I'm considering quitting my job to start a SaaS company. Challenge this decision rather than encouraging me. Identify the biggest risks and assumptions.\" Or: \"I think this architecture is better. Try to prove me wrong.\" This changes the role of the AI from answer generator to thinking partner." },

  { type: "h2", text: "14. Ask for alternatives" },
  { type: "p", text: "Sometimes your first idea isn't necessarily the best approach. Instead of \"How do I build this?\" try \"Give me three different ways to solve this problem and explain the trade-offs.\"" },
  { type: "list", items: ["Technical — \"Give me a simple approach, a scalable approach and a low-cost approach.\"", "Business — \"Give me a conservative, moderate and aggressive strategy.\"", "Travel — \"Give me a budget itinerary, a comfortable itinerary and an experience-focused itinerary.\""] },
  { type: "p", text: "This forces the conversation beyond the first obvious answer." },

  { type: "h2", text: "15. Ask for trade-offs — not just recommendations" },
  { type: "p", text: "AI is often tempted to give you a neat answer. Real-world decisions are rarely neat. Instead of \"Which database should I use?\" try \"Compare PostgreSQL, MongoDB and DynamoDB for this use case. Focus on scalability, operational complexity, cost and developer experience. Don't pick a winner; explain the trade-offs.\"" },
  { type: "callout", text: "You're not asking AI \"Tell me what to think.\" You're asking \"Help me understand the decision.\"" },

  { type: "h2", text: "16. Tell AI what NOT to do" },
  { type: "p", text: "Negative instructions can be surprisingly useful: \"Explain this to a beginner. Don't use mathematical notation.\" Or \"Give me a concise answer. Don't repeat the question.\" Or \"Compare these options without recommending one.\" Or \"Don't invent statistics. If you're uncertain, say so.\" Or \"Use only the information in the document I provided.\"" },
  { type: "p", text: "This reduces the chance that the answer goes in a direction you don't want." },

  { type: "h2", text: "17. Give examples when the style matters" },
  { type: "p", text: "Suppose you want AI to rewrite something. Don't just say \"Make this professional\" — professional can mean many things. Instead: \"Rewrite this in a concise, confident tone. Keep it friendly and avoid corporate jargon. Here's an example of the style I like: [example].\"" },
  { type: "p", text: "Examples give the model something concrete to imitate — sometimes called few-shot prompting, though you don't need to remember the terminology. Just remember: if you want a particular style, show the AI an example." },

  { type: "image", src: assetUrl("/articles/prompting-101/img-4.jpeg"), alt: "Illustration accompanying the section on structuring a complex prompt into goal, context, constraints, and output." },

  { type: "h2", text: "18. Use a structure when the task is complicated" },
  { type: "p", text: "For complex requests, a simple structure works remarkably well: Goal (what I want), Context (what you need to know), Constraints (what you must work within), Output (what I want the answer to look like), Quality bar (what makes the answer useful)." },
  { type: "diagram", text: "Goal: Help me choose a laptop.\n\nContext: I'm a software engineer who occasionally runs AI models locally.\n\nBudget: ₹1.5 lakh maximum.\n\nConstraints: Good battery life, portable, macOS preferred.\n\nOutput: Compare five options in a table.\n\nQuality bar: Focus on real-world performance rather than marketing specifications." },
  { type: "p", text: "That's a strong prompt." },

  { type: "h2", text: "19. One prompt doesn't have to do everything" },
  { type: "p", text: "For complex tasks, breaking the problem into stages can produce better results. Instead of \"Research the market, find a business idea, validate it, design the product, create a marketing plan and write the website,\" break it down:" },
  { type: "list", items: ["Step 1 — \"Identify ten problems in this market that businesses currently solve manually.\"", "Step 2 — \"Now rank these problems by frequency, willingness to pay and ease of automation.\"", "Step 3 — \"Take the top three and analyze competitors.\"", "Step 4 — \"Develop an MVP for the first idea.\"", "Step 5 — \"Create the landing page copy.\""] },
  { type: "p", text: "You're turning one enormous request into a sequence of manageable decisions." },

  { type: "h2", text: "20. But don't over-engineer simple questions" },
  { type: "p", text: "There is another trap. People sometimes discover prompting techniques and then start writing enormous prompts for everything. You don't need \"You are an internationally recognized expert with 25 years of experience...\" to ask \"What is the capital of France?\" Just ask \"What is the capital of France?\"" },
  { type: "callout", text: "Good prompting isn't about making prompts longer. It's about making them clearer." },

  { type: "h2", text: "21. A bad prompt vs. a better prompt" },
  { type: "p", text: "Learning — Weak: \"Teach me Python.\" Better: \"I'm a complete beginner with no programming background. Teach me Python through small practical exercises. Start with the basics and give me one exercise at a time.\"" },
  { type: "p", text: "Writing — Weak: \"Write an email.\" Better: \"Write a polite but firm email to my landlord asking them to fix a leaking bathroom tap. Keep it under 150 words and avoid sounding aggressive.\"" },
  { type: "p", text: "Travel — Weak: \"Plan a trip to Kashmir.\" Better: \"Plan a 6-day Kashmir trip for two people. We enjoy mountains, photography and quieter places more than shopping. Budget is ₹60,000 excluding flights. Give me a day-by-day itinerary and mention approximate travel times.\"" },
  { type: "p", text: "Coding — Weak: \"Fix my Python code.\" Better: \"This Python function is taking 15 seconds to process 100,000 records. Identify the bottleneck, explain why it's slow, and suggest an optimized version. Don't change the function's output.\"" },
  { type: "p", text: "Decision-making — Weak: \"Should I buy this car?\" Better: \"I'm considering this car mainly for city driving but I take 5–6 highway trips a year. My priorities are safety, driving experience and long-term reliability. Analyze the major advantages and drawbacks for my use case and tell me what questions I should ask the dealer before deciding.\"" },

  { type: "image", src: assetUrl("/articles/prompting-101/img-5.jpeg"), alt: "Illustration accompanying the weak-versus-better prompt examples — a visual metaphor comparing a vague request to a specific, well-scoped one." },

  { type: "h2", text: "22. What if the AI gives you a wrong answer?" },
  { type: "p", text: "This is where prompting has a limit. A beautifully written prompt doesn't guarantee a correct answer. AI systems can misunderstand your question, make factual errors, use outdated information, misinterpret data, or produce plausible-sounding nonsense." },
  { type: "p", text: "So for important topics, ask for verification: \"Which parts of your answer are uncertain?\" \"What assumptions are you making?\" \"Give me sources for the factual claims.\" \"Check the latest information before answering.\" \"Separate verified facts from your interpretation.\"" },
  { type: "callout", text: "Don't confuse confidence with correctness. A confident answer can still be wrong." },

  { type: "h2", text: "23. Prompting is really about communication" },
  { type: "p", text: "People sometimes describe prompting as a technical skill. But at its core, good prompting is really about communicating clearly. Think about how you would brief a talented colleague. You wouldn't say \"Do something with this.\" You'd say \"Here's what I'm trying to achieve. Here's the background. Here's what's important. Here's what I don't want. Here's what the final result should look like.\"" },
  { type: "p", text: "That's prompting. The AI is simply a new kind of collaborator." },

  { type: "h2", text: "24. The Prompting 101 cheat sheet" },
  { type: "p", text: "When you're stuck, run through this checklist:" },
  { type: "list", items: [
    "Goal — What exactly do I want? \"I want to choose...\" \"I want to understand...\" \"I want to create...\" \"I want to compare...\"",
    "Context — What does the AI need to know? \"I'm a beginner...\" \"This is for my business...\" \"I'm working with...\"",
    "Constraints — What limits matter? Budget, time, location, experience, technology, length, deadline.",
    "Output — What should the answer look like? Table, bullets, step-by-step guide, email, code, executive summary.",
    "Iterate — What should change after seeing the first answer? \"Make it simpler.\" \"Go deeper.\" \"Give me alternatives.\" \"Challenge this.\" \"Focus on X.\"",
  ] },

  { type: "image", src: assetUrl("/articles/prompting-101/img-6.jpeg"), alt: "Illustration accompanying the Prompting 101 cheat sheet — a visual summary of goal, context, constraints, output, and iteration." },

  { type: "h2", text: "25. The simplest prompt formula" },
  { type: "p", text: "If you remember nothing else, remember this: \"I want [GOAL]. Here's [CONTEXT]. My constraints are [CONSTRAINTS]. Give me [OUTPUT].\"" },
  { type: "p", text: "For example: \"I want to learn Machine Learning. I'm a software engineer but I have very little ML experience. I can spend five hours a week for three months. Give me a practical learning roadmap with projects rather than just courses.\" That's already a very good prompt. You don't need a secret formula. You don't need 47 instructions. You need to tell the AI what you're trying to accomplish." },

  { type: "h2", text: "26. The biggest upgrade isn't a better prompt" },
  { type: "p", text: "Here's the funny thing about prompting. The most effective AI users aren't necessarily the people who know the most \"prompt engineering tricks.\" They're often the people who are good at defining a problem, providing relevant context, setting constraints, recognizing a bad answer, asking useful follow-up questions, and iterating until the result is useful." },
  { type: "callout", text: "Good prompting isn't about finding the magic words. It's about learning how to communicate with a very capable, but imperfect, collaborator." },
  { type: "p", text: "And once you start thinking about prompts that way, the whole subject becomes much simpler. Better prompts. Better conversations. Better results." },
];
